## EXPLORATORY DATA ANALYSIS ON WAETHER HISTORY DATASET

BY CHIBUZO AKANA

Data source - Kaggle.com

### TABLE OF CONTENTS

- INTRODUCTION
- IMPORT LIBRARIES
- LOAD DATA
- CLEAN DATA
- PREPARE DATA
- ANALYSE DATA

#### INTRODUCTION

This report is based on a weather history report. The major variables that will be looked into are; Temperature, Humidity, Wind Speed, Pressure, Weather Condition. Some questions were answered through this report that covered the analysis.

#### IMPORT LIBRARIES

In [27]:
import pandas as pd
import numpy as np

#### LOAD DATA

In [28]:
df = pd.read_csv('weatherHistory.csv')
df

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [29]:
# This gives the number of rows and columns in the dataset
df.shape

(96453, 12)

In [30]:
# This shows info about the nature of data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            96453 non-null  object
 1   Summary                   96453 non-null  object
 2   Precip Type               95936 non-null  object
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  float64
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  float64
 10  Pressure (millibars)      96453 non-null  float64
 11  Daily Summary             96453 non-null  object
dtypes: float64(8), object(4)
memory usage: 8.8+ MB

In [31]:
# This shows the data types
df.dtypes

Formatted Date               object
Summary                      object
Precip Type                  object
Temperature (C)             float64
Apparent Temperature (C)    float64
Humidity                    float64
Wind Speed (km/h)           float64
Wind Bearing (degrees)      float64
Visibility (km)             float64
Loud Cover                  float64
Pressure (millibars)        float64
Daily Summary                object
dtype: object

In [32]:
df.rename(columns = {'Formatted Date': 'Date', 'Summary':'Weather', 'Precip Type':'Precip', 'Temperature (C)':'Temp', 'Apparent Temperature (C)':'App_Temp', 'Humidity':'Humi', 'Wind Speed (km/h)':'Wind_Speed', 'Wind Bearing (degrees)':'Wind_Bear', 'Visibility (km)':'Visibility', 'Loud Cover':'Loud', 'Pressure (millibars)':'Pressure', 'Daily Summer':'Daily_Weather'}, inplace=True)
df

,Date,Weather,Precip,Temp,App_Temp,Humi,Wind_Speed,Wind_Bear,Visibility,Loud,Pressure,Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

#### ANALYSE DATA

### Q. 1)  Find all the unique 'Wind Speed' values in the data.

In [33]:
df.Wind_Speed.unique()

array([14.1197, 14.2646,  3.9284, ..., 37.0622, 35.5971, 30.751 ])

In [34]:
df.Wind_Speed.nunique()

2484

### Q. 2) Find the number of times when the 'Weather is exactly Clear'.

In [35]:
df.groupby('Weather').get_group('Clear').head(20)

,Date,Weather,Precip,Temp,App_Temp,Humi,Wind_Speed,Wind_Bear,Visibility,Loud,Pressure,Daily Summary
223,2006-04-18 07:00:00.000 +0200,Clear,rain,8.688889,8.688889,0.93,1.4329,290.0,5.8443,0.0,1012.96,Partly cloudy until night.
309,2006-04-20 21:00:00.000 +0200,Clear,rain,12.266667,12.266667,0.99,8.0500,320.0,6.1985,0.0,1015.76,Foggy starting overnight continuing until morn...
337,2006-04-22 01:00:00.000 +0200,Clear,rain,9.355556,8.633333,0.96,6.4239,321.0,3.3649,0.0,1017.56,Foggy starting overnight continuing until morn...
338,2006-04-22 02:00:00.000 +0200,Clear,rain,9.861111,9.861111,0.96,3.2361,319.0,4.4597,0.0,1016.16,Foggy starting overnight continuing until morn...
357,2006-04-22 21:00:00.000 +0200,Clear,rain,12.494444,12.494444,0.91,3.9445,197.0,9.9820,0.0,1015.51,Foggy starting overnight continuing until morn...
358,2006-04-22 22:00:00.000 +0200,Clear,rain,12.244444,12.244444,0.89,1.5295,140.0,15.8263,0.0,1015.72,Foggy starting overnight continuing until morn...
359,2006-04-22 23:00:00.000 +0200,Clear,rain,11.416667,11.416667,0.92,2.9624,275.0,14.9569,0.0,1015.79,Foggy starting overnight continuing until morn...
360,2006-04-23 00:00:00.000 +0200,Clear,rain,10.555556,10.555556,0.95,6.0375,290.0,14.8120,0.0,1015.83,Foggy in the morning.
361,2006-04-23 01:00:00.000 +0200,Clear,rain,10.466667,10.466667,0.93,3.0751,270.0,9.8049,0.0,1015.95,Foggy in the morning.
363,2006-04-23 03:00:00.000 +0200,Clear,rain,9.355556,9.355556,0.96,1.5295,100.0,4.0250,0.0,1015.82,Foggy in the morning.
386,2006-04-24 02:00:00.000 +0200,Clear,rain,12.383333,12.383333,0.80,4.6207,172.0,14.1680,0.0,1019.59,Partly cloudy until evening.
391,2006-04-24 07:00:00.000 +0200,Clear,rain,10.911111,10.911111,0.99,1.6100,210.0,4.1216,0.0,1018.62,Partly cloudy until evening.
392,2006-04-24 08:00:00.000 +0200,Clear,rain,14.838889,14.838889,0.82,2.6565,193.0,8.3398,0.0,1019.08,Partly cloudy until evening.
393,2006-04-24 09:00:00.000 +0200,Clear,rain,18.800000,18.800000,0.65,1.5295,140.0,9.9820,0.0,1019.11,Partly cloudy until evening.
394,2006-04-24 10:00:00.000 +0200,Clear,rain,21.094444,21.094444,0.49,4.8783,199.0,9.9820,0.0,1019.50,Partly cloudy until evening.
406,2006-04-24 22:00:00.000 +0200,Clear,rain,14.905556,14.905556,0.72,3.7513,136.0,15.8263,0.0,1019.91,Partly cloudy until evening.
407,2006-04-24 23:00:00.000 +0200,Clear,rain,13.083333,13.083333,0.87,3.4132,185.0,14.9569,0.0,1020.02,Partly cloudy until evening.
408,2006-04-25 00:00:00.000 +0200,Clear,rain,12.711111,12.711111,0.89,3.2522,169.0,15.8263,0.0,1020.11,Partly cloudy starting in the morning.
409,2006-04-25 01:00:00.000 +0200,Clear,rain,12.127778,12.127778,0.89,3.1717,148.0,14.9086,0.0,1020.12,Partly cloudy starting in the morning.
410,2006-04-25 02:00:00.000 +0200,Clear,rain,11.811111,11.811111,0.84,4.9910,68.0,14.9569,0.0,1018.38,Partly cloudy starting in the morning.

#### Q. 3) Find the number of times when the 'Wind Speed was above 5 km/h'.

In [36]:
df[df.Wind_Speed > 5].tail()

,Date,Weather,Precip,Temp,App_Temp,Humi,Wind_Speed,Wind_Bear,Visibility,Loud,Pressure,Daily Summary
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

### Q. 4) Find out all the Null Values in the data.

In [37]:
df.isnull().sum()

Date               0
Weather            0
Precip           517
Temp               0
App_Temp           0
Humi               0
Wind_Speed         0
Wind_Bear          0
Visibility         0
Loud               0
Pressure           0
Daily Summary      0
dtype: int64

In [38]:
df.isnull().any()

Date             False
Weather          False
Precip            True
Temp             False
App_Temp         False
Humi             False
Wind_Speed       False
Wind_Bear        False
Visibility       False
Loud             False
Pressure         False
Daily Summary    False
dtype: bool

### Q. 5) What is the mean 'Visibility' ?

In [39]:
df.head(2)

,Date,Weather,Precip,Temp,App_Temp,Humi,Wind_Speed,Wind_Bear,Visibility,Loud,Pressure,Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.

In [40]:
df.Visibility.mean()

10.347324929237148

### Q. 6) What is the Standard Deviation of 'Pressure'  in this data?

In [41]:
df.Pressure.std()

116.96990568258147

### Q. 7) What is the Variance of 'Humidity' in this data ?

In [42]:
df.Humi.var()

0.03820959171844407

### Q. 8) Find all instances when 'Rain until afternoon' was recorded.

In [43]:
df['Daily Summary'].value_counts()

Mostly cloudy throughout the day.                                                                       20085
Partly cloudy throughout the day.                                                                        9981
Partly cloudy until night.                                                                               6169
Partly cloudy starting in the morning.                                                                   5184
Foggy in the morning.                                                                                    4201
                                                                                                        ...
Breezy starting overnight continuing until morning and foggy overnight.                                    24
Mostly cloudy throughout the day and breezy starting overnight continuing until afternoon.                 24
Partly cloudy starting in the morning and breezy starting in the afternoon continuing until evening.       24
Rain until afternoon.                                                                                      24
Foggy starting overnight continuing until morning and breezy in the afternoon.                             23
Name: Daily Summary, Length: 214, dtype: int64

In [44]:
# From above, "Rain until afternoon" was recorded 24 times

### Q. 9) Find all instances when 'Wind Speed is above 24' and 'Visibility is above 25'.

In [45]:
df[(df.Wind_Speed < 14) & (df.Visibility < 15)]

,Date,Weather,Precip,Temp,App_Temp,Humi,Wind_Speed,Wind_Bear,Visibility,Loud,Pressure,Daily Summary
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
5,2006-04-01 05:00:00.000 +0200,Partly Cloudy,rain,9.222222,7.111111,0.85,13.9587,258.0,14.9569,0.0,1016.66,Partly cloudy throughout the day.
6,2006-04-01 06:00:00.000 +0200,Partly Cloudy,rain,7.733333,5.522222,0.95,12.3648,259.0,9.9820,0.0,1016.72,Partly cloudy throughout the day.
8,2006-04-01 08:00:00.000 +0200,Partly Cloudy,rain,10.822222,10.822222,0.82,11.3183,259.0,9.9820,0.0,1017.37,Partly cloudy throughout the day.
9,2006-04-01 09:00:00.000 +0200,Partly Cloudy,rain,13.772222,13.772222,0.72,12.5258,279.0,9.9820,0.0,1017.22,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96389,2016-09-07 08:00:00.000 +0200,Partly Cloudy,rain,17.811111,17.811111,0.90,12.1555,22.0,13.7333,0.0,1021.36,Partly cloudy throughout the day.
96390,2016-09-07 09:00:00.000 +0200,Partly Cloudy,rain,19.977778,19.977778,0.84,11.4310,32.0,11.9784,0.0,1021.35,Partly cloudy throughout the day.
96410,2016-09-08 05:00:00.000 +0200,Mostly Cloudy,rain,16.738889,16.738889,0.90,10.6260,2.0,14.1680,0.0,1017.74,Partly cloudy starting overnight.
96434,2016-09-09 05:00:00.000 +0200,Clear,rain,15.016667,15.016667,0.90,2.7048,359.0,14.9569,0.0,1014.55,Partly cloudy starting in the morning.
96437,2016-09-09 08:00:00.000 +0200,Partly Cloudy,rain,19.561111,19.561111,0.75,3.7191,12.0,14.9569,0.0,1015.28,Partly cloudy starting in the morning.

### Q. 10) What is the Mean value of each column against each 'Temperature' ?

In [46]:
df.Temp.mean()

11.932678437511868

### Q. 11) What is the Minimum & Maximum value of each column against each 'Temperature' ?

In [47]:
df.Temp.min()

-21.822222222222223

In [48]:
df.Temp.max()

39.90555555555555

### Q. 12) Find all instances when 'Weather is Clear' or 'Visibility is above 40'.

In [49]:
df[(df['Weather'] =='Clear') | (df.Visibility > 10)]

,Date,Weather,Precip,Temp,App_Temp,Humi,Wind_Speed,Wind_Bear,Visibility,Loud,Pressure,Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

### Q. 13) Find all instances when :
A. 'Weather is Clear' and 'Relative Humidity is greater than 0.5'
or
B. 'Visibility is above 40'

In [50]:
df[(df['Weather'] == 'Clear') & (df['Humi'] > 0.5) | (df['Visibility'] > 14)]

,Date,Weather,Precip,Temp,App_Temp,Humi,Wind_Speed,Wind_Bear,Visibility,Loud,Pressure,Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.